services:

  postgres:
    image: postgres:15
    container_name: strikeiq-postgres
    environment:
      POSTGRES_USER: strikeiq
      POSTGRES_PASSWORD: strikeiq123
      POSTGRES_DB: strikeiq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: strikeiq-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: